# Generated by Django 5.1.1 on 2024-09-30 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='customer',
            name='avatar_url',
            field=models.CharField(default='none', max_length=2083),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='mi',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
    ]
