# Generated by Django 5.1.1 on 2024-10-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0003_rename_first_name_customer_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='mobile',
        ),
        migrations.AddField(
            model_name='customer',
            name='pword',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='uname',
            field=models.CharField(default='NA', max_length=30),
            preserve_default=False,
        ),
    ]
