# Generated by Django 5.1.1 on 2024-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0003_rename_first_name_customer_fname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model_directory',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='model_file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
