# Generated by Django 5.1.1 on 2024-10-01 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0004_rename_phone_customer_mobile_customer_pword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='uname',
            new_name='username',
        ),
    ]
