# Generated by Django 5.1.1 on 2024-10-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0004_product_model_directory_product_model_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
