# Generated by Django 5.1.1 on 2024-10-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0005_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
