# Generated by Django 5.1.1 on 2024-10-08 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space_tigersapp', '0007_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
